---
kind: pipeline
name: default
type: docker

steps:
  - name: html-proofer
    image: ruby
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      LANG: C.UTF-8
    commands:
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      - gem install html-proofer
      - htmlproofer --disable-external ./_site
    when:
      branch:
        - master
