# Site settings
title: Aolab
description: "Let's light the lamp<br>June 2015 - July 2017"
repository: "AoLab/AoLab.github.io"

# Secondary Parameters
header-img: img/header.jpg
headercolor: "#FFFFFF"
logo: img/logo.png

# Tertiary Parameters
github_username: Aolab
project_repository: Aolab.github.io
g-analytics: UA-75881392-1
altmetric: true

# Build settings
gems:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
