# Site settings
title: "Amirkabir University of Technology IoT Laboratory"
email: ":)"
description: "Amirkabir University of Technology IoT Laboratory Website"
# the base hostname & protocol for your site
baseurl: ""
encoding: utf8
# the subpath of your site, e.g. /blog/
url: ""
lang: "en"

github_username: "AoLab"

# Build settings
markdown: kramdown
